services:
    client:
        image: node:20-alpine
        container_name: lofi-downloader
        volumes:
            - .:/source
        working_dir: /source
        ports:
            - 8080:8080
        command: sh -c "npm install && npm run serve"